
const movies = [
  {
    name: "Aladdin",
    badge: "PG",
    time: "2h 8mins",
    description: "A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.",
    director: "Guy Ritchie",
    writer:"John August (screenplay by), Guy Ritchie (screenplay by)",
    stars:"Will Smith, Mena Massoud, Naomi Scott",
    image:"imgs/aladdin.jpg",
    cinemas:["cinema_1","cinema_2","cinema_3","cinema_4"],
    cinema_1:["Sep 14","Sep 15","Sep 13"],
    cinema_2:["Sep 7", "Sep 8"],
    cinema_3:["Sep 9", "Sep 10"],
    cinema_4:["Sep 11", "Sep 12"]
  },
  {
    name: "Tangled",
    badge: "PG",
    time: "1h 40mins",
    description: "The magically long-haired Rapunzel has spent her entire life in a tower, but now that a runaway thief has stumbled upon her, she is about to discover the world for the first time, and who she really is.",
    director: "Nathan Greno, Byron Howard",
    writer:"Dan Fogelman (screenplay by), Jacob Grimm (based upon the fairy tale Rapunzel by) (as the Brothers Grimm)",
    stars:"Mandy Moore, Zachary Levi, Donna Murphy",
    image:"imgs/tangled.jpg",
    cinemas:["cinema_1","cinema_2","cinema_3","cinema_4"],
    cinema_2:["Sep 14","Sep 15","Sep 13"],
    cinema_3:["Sep 7", "Sep 8"],
    cinema_4:["Sep 9", "Sep 10"],
    cinema_1:["Sep 11", "Sep 12"]
  },
  {
    name: "Ant-Man",
    badge: "PG-13",
    time: "1h 57mins",
    description: "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.",
    director: "Peyton Reed",
    writer:"Edgar Wright (screenplay by), Joe Cornish (screenplay by)",
    stars:"Paul Rudd, Michael Douglas, Corey Stoll",
    image:"imgs/ant-man.jfif",
    cinemas:["cinema_1","cinema_2","cinema_3","cinema_4"],
    cinema_3:["Sep 4","Sep 15","Sep 6"],
    cinema_4:["Sep 7", "Sep 13"],
    cinema_1:["Sep 9", "Sep 10"],
    cinema_2:["Sep 11", "Sep 12"]
  },
  {
    name: "Infinity War",
    badge: "PG-13",
    time: "2h 29mins",
    description: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    director: "Anthony Russo, Joe Russo",
    writer:"Christopher Markus (screenplay by), Stephen McFeely (screenplay by)",
    stars:"Robert Downey Jr., Chris Hemsworth, Mark Ruffalo",
    image:"imgs/infinity-war.jfif",
    cinemas:["cinema_1","cinema_2","cinema_3","cinema_4"],
    cinema_4:["Sep 4","Sep 13","Sep 6"],
    cinema_1:["Sep 7", "Sep 8"],
    cinema_2:["Sep 9", "Sep 10"],
    cinema_3:["Sep 11", "Sep 12"]
  },
  {
   name: "Guardians of the Galaxy",
    badge: "PG-13",
    time: "2h 1mins",
    description: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    director: "James Gunn",
    writer:"James Gunn, Nicole Perlman",
    stars:"Chris Pratt, Vin Diesel, Bradley Cooper",
    image:"imgs/guardians-of-the-galaxy.jfif",
    cinemas:["cinema_1","cinema_2","cinema_3","cinema_4"],
    cinema_2:["Sep 13","Sep 14","Sep 15"],
    cinema_3:["Sep 16", "Sep 17"],
    cinema_4:["Sep 18", "Sep 19"],
    cinema_1:["Sep 20", "Sep 21"]
  },
  {
    name: "Captain Marvel",
    badge: "PG-13",
    time: "2h 3mins",
    description: "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
    director: "Anna Boden, Ryan Fleck",
    writer:"Anna Boden (screenplay by), Ryan Fleck (screenplay by)",
    stars:"Brie Larson, Samuel L. Jackson, Ben Mendelsohn",
    image:"imgs/captain-marvel.jfif",
    cinemas:["cinema_1","cinema_2","cinema_3","cinema_4"],
    cinema_3:["Sep 13","Sep 14","Sep 15"],
    cinema_4:["Sep 16", "Sep 17"],
    cinema_1:["Sep 18", "Sep 19"],
    cinema_2:["Sep 20", "Sep 21"]
  },
  {
    name: "TRON: Legacy",
    badge: "PG-13",
    time: "2h 5mins",
    description: "The son of a virtual world designer goes looking for his father and ends up inside the digital world that his father designed. He meets his father's corrupted creation and a unique ally who was born inside the digital world.",
    director: "Joseph Kosinski",
    writer:"Edward Kitsis (screenplay), Adam Horowitz (screenplay)",
    stars:"Jeff Bridges, Garrett Hedlund, Olivia Wilde",
    image:"imgs/tron.jfif",
    cinemas:["cinema_1","cinema_2","cinema_3","cinema_4"],
    cinema_4:["Sep 13","Sep 14","Sep 15"],
    cinema_1:["Sep 16", "Sep 17"],
    cinema_2:["Sep 18", "Sep 19"],
    cinema_3:["Sep 20", "Sep 21"]
  },
  {
    name: "The Lion King",
    badge: "PG",
    time: "1h 58mins",
    description: "After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.",
    director: "Jon Favreau",
    writer:"Jeff Nathanson (screenplay by), Brenda Chapman (story)",
    stars:"Donald Glover, Beyoncé, Seth Rogen",
    image:"imgs/lion-king.jpg",
    cinemas:["cinema_1","cinema_2","cinema_3","cinema_4"],
    cinema_1:["Sep 13","Sep 14","Sep 15"],
    cinema_2:["Sep 16", "Sep 17"],
    cinema_3:["Sep 18", "Sep 19"],
    cinema_4:["Sep 20", "Sep 21"]
  },
  {
    name: "Moana",
    badge: "PG",
    time: "1h 57mins",
    description: "In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana's island, she answers the Ocean's call to seek out the Demigod to set things right.",
    director: "Ron Clements, John Musker",
    writer:"Jared Bush (screenplay by), Ron Clements (story by)",
    stars:"Auli'i Cravalho, Dwayne Johnson, Rachel House",
    image:"imgs/moana.jpg",
    cinemas:["cinema_1","cinema_2","cinema_3"],
    cinema_1:["Sep 22"],
    cinema_2:["Sep 23"],
    cinema_3:["Sep 24"],
    cinema_4:["Sep 24"]
  },
  {
    name: "A Wrinkle in Time",
    badge: "PG",
    time: "1h 49mins",
    description: "After the disappearance of her scientist father, three peculiar beings send Meg, her brother, and her friend to space in order to find him.",
    director: "Ava DuVernay",
    writer:"Jennifer Lee (screenplay by), Jeff Stockwell (screenplay by)",
    stars:"Storm Reid, Oprah Winfrey, Reese Witherspoon",
    image:"imgs/wrinkle-in-time.jpg",
    cinemas:["cinema_1","cinema_2","cinema_3"],
    cinema_2:["Sep 22"],
    cinema_3:["Sep 23"],
    cinema_1:["Sep 24"],
    cinema_4:["Sep 24"]
  },
  {
    name: "Enchanted",
    badge: "PG",
    time: "1h 47mins",
    description: "A young maiden in a land called Andalasia, who is prepared to be wed, is sent away to New York City by an evil queen, where she falls in love with a lawyer.",
    director: "Kevin Lima",
    writer:"Bill Kelly",
    stars:"Amy Adams, Susan Sarandon, James Marsden",
    image:"imgs/enchanted.jpg",
    cinemas:["cinema_1","cinema_2","cinema_3"],
    cinema_3:["Sep 22"],
    cinema_1:["Sep 23"],
    cinema_2:["Sep 24"],
    cinema_4:["Sep 24"]
  },
  {
    name: "Beauty and the Beast",
    badge: "PG",
    time: "2h 10mins",
    description: "A selfish prince is cursed to become a monster for the rest of his life, unless he learns to fall in love with a beautiful young woman he keeps prisoner.",
    director: "Bill Condon",
    writer:"Bill Kelly",
    stars:" Emma Watson, Dan Stevens, Luke Evans",
    image:"imgs/beauty-and-the-beast.jfif",
    cinemas:["cinema_4"],
    cinema_1:["Sep 23"],
    cinema_2:["Sep 24"],
    cinema_3:["Sep 22"],
    cinema_4:["Sep 22","Sep 23","Sep 24"]
  }]

if(typeof(Storage) !== "undefined") {
  localStorage.setItem('movies', JSON.stringify(movies));
}

